import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Body bg: hsl(238, 27%, 12%) - #161727
// Sidebar bg color: rgba(0,0,0,.1)
// Sidebar border color: hsl(242, 10%, 20%) - #2e2e38

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#161727]">{children}</body>
    </html>
  );
}
